apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf:  |
    server {
      listen   443;
      listen  [::]:443;
      server_name yamangulov.ru;
      access_log  /var/log/nginx/host.access.log  main;
      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }

