apiVersion: v1
kind: Service
metadata:
  name: two-apps-srv
spec:
  type: NodePort
  selector:
    app: two-apps
  ports:
  - name: nginx-http
    port: 80
    targetPort: 80
    nodePort: 31080
  - name: multitool-http
    port: 1180
  - name: multitool-https
    port: 11443