---
- name: Check repo list is correct
  become: true
  ansible.builtin.command: yum list yava*
  register: returned
  ignore_errors: yes
- name: Correct AppStream repo
  become: true
  ansible.builtin.shell: |
    cd /etc/yum.repos.d/
    sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
    dnf update libmodulemd -y
  when: returned.rc != 0
- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_subversion }}.x86_64.rpm"
    dest: "./vector-{{ vector_subversion }}.x86_64.rpm"

