apiVersion: v1
kind: Service
metadata:
  name: two-apps-svc-nodeport
spec:
  type: NodePort
  selector:
    app: two-apps
  ports:
  - name: nginx-http-nodeport
    port: 80
    targetPort: 80
    nodePort: 31000
