apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-apps
  labels:
    app: two-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: two-apps
  template:
    metadata:
      labels:
        app: two-apps
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.3
        ports:
        - containerPort: 80
      - name: network-multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "1180"
        - name: HTTPS_PORT
          value: "11443"
        ports:
        - containerPort: 1180
          name: http
        - containerPort: 11443
          name: https
