apiVersion: v1
kind: Pod
metadata:
  name: multitool
  labels:
    app: multitool
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool
    env:
    - name: HTTP_PORT
      value: "1280"
    - name: HTTPS_PORT
      value: "12443"
    ports:
    - containerPort: 1280
      name: http
    - containerPort: 12443
      name: https

