apiVersion: v1
kind: Service
metadata:
  name: service-for-update
spec:
  ports:
    - name: web-nginx
      port: 9001
      targetPort: 80
    - name: web-network-multitool
      port: 9002
      targetPort: 8080
  selector:
    app: main