apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-apps
  labels:
    app: two-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-apps
  template:
    metadata:
      labels:
        app: two-apps
      name: two-apps
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'while true; do echo test >> /output/test.txt; sleep 5; done']
        volumeMounts:
        - mountPath: /output
          name: vol

      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - mountPath: /input
          name: vol

      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: local-share

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-share
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-share
spec:
  volumeMode: Filesystem
  capacity:
    storage: 20Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/local-share


