apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.129.0.25
  share: /srv/nfs
reclaimPolicy: Delete
mountOptions:
- hard
- nfsvers=4.0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-volume
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-apps
  labels:
    app: nfs-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-apps
  template:
    metadata:
      name: multitool
      labels:
        app: nfs-apps
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - mountPath: /srv/nfs
          name: vol

      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: nfs-volume

