---
- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.11.0"
  name: clickhouse
- src: https://github.com/yamangulov/vector-role
  scm: git
  version: "0.0.1"
  name: vector
- src: https://github.com/yamangulov/lighthouse-role
  scm: git
  version: "0.0.1"
  name: lighthouse