version: '3.9'

services:

  postgres_12:
    container_name: postgres_12
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ../src/main/resources/data/postgres:/var/lib/postgresql/data
      - ../src/main/resources/data/backups:/var/lib/postgresql/backups
    ports:
      - "25432:5432"

#  использовалось для задачи 6 - бекап и восстановление
#  postgres_12-2:
#    container_name: postgres_12_2
#    image: postgres:12
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      PGDATA: /var/lib/postgresql/data2
#    volumes:
#      - ../src/main/resources/data/postgres:/var/lib/postgresql/data2
#      - ../src/main/resources/data/backups:/var/lib/postgresql/backups
#    ports:
#      - "45432:5432"

