---
- name: Install vector
  hosts: vector
  handlers:
    - name: Start vector
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_subversion }}.x86_64.rpm"
        dest: "./vector-{{ vector_subversion }}.x86_64.rpm"
    - name: Install vector package
      become: true
      ansible.builtin.yum:
        name:
          - vector-{{ vector_subversion }}.x86_64.rpm
      notify: Start vector