apiVersion: v1
kind: Pod
metadata:
  labels:
    app: echoserver
  name: netology-web
  namespace: default
spec:
  containers:
  - name: echoserver
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2


