apiVersion: v1
kind: Service
metadata:
  labels:
    app: echoserver
  name: netology-svc
  namespace: default
spec:
  selector:
    app: echoserver
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 8080